/**
 * `@build-room/journal` — the four §6.2 canonical serialization contracts
 * of the Build Room command journal, as pure encoders.
 *
 * PURE: zero I/O beyond `node:crypto` hashing. No database code, no
 * chain-head, no append path — the journal store and append protocol are
 * the step-2b layer (`docs/command-journal-contract.md` §3–§5); this
 * package is the ratified byte layer they consume.
 *
 * Specs: `packages/journal/specs/serialization-{a,b,c,d}-*.md`. Golden
 * vectors: `packages/journal/vectors/`, generated by the implementation,
 * never hand-authored (contract §6.2).
 */

export {
  GENESIS_CHAIN_HASH,
  chainHash,
} from './chain.js';

export {
  ENVELOPE_VERSION,
  SPEC_ID_A,
  encodeEnvelope,
  envelopeDigest,
  type NormalizedCommandEnvelope,
} from './envelope.js';

export {
  SPEC_ID_B,
  encodePlanDoc,
  planHash,
  type CanonicalDocument,
  type CanonicalValue,
} from './plandoc.js';

export {
  COMMAND_EVENT_TYPES,
  COMMAND_ID_PREFIX,
  RECORD_CLASS_COMMAND,
  RESOLUTION_DETERMINATIONS,
  RESOLUTION_SEMANTICS,
  SPEC_ID_C,
  encodeCommandEventRow,
  type CommandEventRow,
  type CommandEventType,
  type LifecycleEventRef,
  type ResolutionDetermination,
  type ResolutionSemantics,
} from './event-row.js';

export {
  DECISION_ACTOR,
  DECISION_EVENTS,
  NO_PLANDOC_EFFECTIVE_STATES,
  RECORD_CLASS_DECISION,
  SPEC_ID_D,
  effectivePlanBearingState,
  encodeDecisionRecordRow,
  planHashRequired,
  type DecisionEvent,
  type DecisionRecordRow,
} from './decision-row.js';

export {
  isCanonicalRecordedAt,
  isCanonicalSeq,
  isHex64,
  sha256Hex,
} from './bytes.js';
