/**
 * `@build-room/journal` — the four §6.2 canonical serialization contracts
 * of the Build Room command journal, plus the §7.1–7.3 stop-gate proof
 * substrate built on them.
 *
 * Two layers, deliberately separate:
 *
 *   BYTES (`bytes`, `chain`, `envelope`, `plandoc`, `event-row`,
 *     `decision-row`) — pure encoders, zero I/O beyond `node:crypto`
 *     hashing. Specs: `packages/journal/specs/serialization-{a,b,c,d}-*.md`.
 *     Golden vectors: `packages/journal/vectors/`, generated by the
 *     implementation, never hand-authored (contract §6.2).
 *
 *   PROOF SUBSTRATE (`redact`, `store`, `dispatch`) — the append-only
 *     singular journal and the fail-closed dispatch path that prove
 *     stop-gate items §7.1–7.3 against those bytes. `store` is IN-MEMORY:
 *     the ruled production locus is Neon Postgres under a sole-writer
 *     grant (`docs/command-journal-contract.md` §3 [RULED]), and this
 *     package introduces none of it. What it does carry is the same
 *     invariant set, provable without infrastructure.
 */

export {
  GENESIS_CHAIN_HASH,
  chainHash,
} from './chain.js';

export {
  ENVELOPE_VERSION,
  SPEC_ID_A,
  encodeEnvelope,
  envelopeDigest,
  type NormalizedCommandEnvelope,
} from './envelope.js';

export {
  SPEC_ID_B,
  encodePlanDoc,
  planHash,
  type CanonicalDocument,
  type CanonicalValue,
} from './plandoc.js';

export {
  COMMAND_EVENT_TYPES,
  COMMAND_ID_PREFIX,
  RECORD_CLASS_COMMAND,
  RESOLUTION_DETERMINATIONS,
  RESOLUTION_SEMANTICS,
  SPEC_ID_C,
  encodeCommandEventRow,
  type CommandEventRow,
  type CommandEventType,
  type LifecycleEventRef,
  type ResolutionDetermination,
  type ResolutionSemantics,
} from './event-row.js';

export {
  DECISION_ACTOR,
  DECISION_EVENTS,
  NO_PLANDOC_EFFECTIVE_STATES,
  RECORD_CLASS_DECISION,
  SPEC_ID_D,
  effectivePlanBearingState,
  encodeDecisionRecordRow,
  planHashRequired,
  type DecisionEvent,
  type DecisionRecordRow,
} from './decision-row.js';

export {
  isCanonicalRecordedAt,
  isCanonicalSeq,
  isHex64,
  sha256Hex,
} from './bytes.js';

export {
  REDACTED,
  containsCredentialMaterial,
  redactArgv,
} from './redact.js';

// `resetActiveJournalForTests` is deliberately NOT re-exported: it drops the
// singularity latch, and a consumer able to do that through the package's
// public surface would undercut the §1 claim this package makes. Tests reach
// it through `./store.js` directly. The `corrupt*ForTest` methods on
// MemoryCommandJournal remain reachable and are a known residual — closing
// that needs a separate `/testing` entry point.
export {
  JournalAppendError,
  MemoryCommandJournal,
  getActiveJournal,
  type ChainedJournalRecord,
  type JournalAppendErrorCode,
  type VerifyResult,
} from './store.js';

export {
  DispatchError,
  dispatchGovernedCommand,
  executeWithoutJournal,
  normalizeForJournal,
  requireJournalOrThrow,
  type DispatchErrorCode,
  type DispatchResult,
  type GovernedCommandRequest,
} from './dispatch.js';
